name: Deploy to WordPress.org
on: workflow_call
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - name: WordPress Theme Deploy
      uses: Codeinwp/action-wordpress-theme-deploy@primary
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
